controller_list:
  - name: fake_iiwa_pink_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_pink_joint_1
      - iiwa_pink_joint_2
      - iiwa_pink_joint_3
      - iiwa_pink_joint_4
      - iiwa_pink_joint_5
      - iiwa_pink_joint_6
      - iiwa_pink_joint_7
  - name: fake_space_assembly_part_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: iiwa_pink_arm
    pose: home